=== dimitar-t/XML-Course-Project/reservoirs.dtd
<!ELEMENT reservoirInfo ((regions, rivers, reservoirs))>
<!ELEMENT regions ((region+))>
<!ELEMENT region EMPTY>
<!ATTLIST region
		 id ID #REQUIRED
		 name CDATA #REQUIRED>
<!ELEMENT rivers ((river+))>
<!ELEMENT river EMPTY>
<!ATTLIST river
		 id ID #REQUIRED
		 name CDATA #REQUIRED>
<!ELEMENT reservoirs ((reservoir+))>
<!ELEMENT reservoir (name, depth, damHeight, length, coordinates, area, water_capacity)>
<!ATTLIST reservoir 
		 id ID #REQUIRED
		 regionId IDREF #REQUIRED
		 riverId IDREF #REQUIRED
		 photo ENTITIES #IMPLIED>
<!ELEMENT name (#PCDATA)>
<!ELEMENT depth (#PCDATA)>
<!ELEMENT damHeight (#PCDATA)>
<!ELEMENT length (#PCDATA)>
<!ELEMENT coordinates (latitude, longitude)>
<!ELEMENT latitude (#PCDATA)>
<!ELEMENT longitude (#PCDATA)>
<!ELEMENT area (#PCDATA)>
<!ELEMENT water_capacity (#PCDATA)>

=== dimitar-t/XML-Course-Project/reservoirs.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE reservoirInfo SYSTEM "reservoirs.dtd">
<reservoirInfo>
        <regions>
                <region id="reg_1" name="Северозапад"></region>
                <region id="reg_2" name="Североизток"></region>
                <region id="reg_3" name="Югозапад"></region>
                <region id="reg_4" name="Югоизток"></region>
        </regions>
        
        <rivers>
                <river id="riv_1" name="Тунджа"></river>
                <river id="riv_2" name="Въча"></river>
                <river id="riv_3" name="Камчия"></river>
                <river id="riv_4" name="Доспат" />
                <river id="riv_5" name="Мътница" />
        </rivers>
        <reservoirs>
                <reservoir id="res_1" regionId="reg_3" riverId="riv_2" photo="vucha">
                        <name>Въча</name>
                        <depth>160</depth>
                        <damHeight>144.5</damHeight>
                        <length>10</length>
                        <coordinates>
                                <latitude>41.8989633</latitude>
                                <longitude>24.3625031</longitude>
                        </coordinates>
                        <area>5</area>
                        <water_capacity>226 120 000</water_capacity>
                </reservoir>
                <reservoir id="res_2" regionId="reg_3" riverId="riv_4" photo="dospat">
                        <name>Доспат</name>
                        <depth>60</depth>
                        <damHeight>60.5</damHeight>
                        <length>19</length>
                        <coordinates>
                                <latitude>41.691940</latitude>
                                <longitude>24.092375</longitude>
                        </coordinates>
                        <area>18,3</area>
                        <water_capacity>449 220 000</water_capacity>
                </reservoir>
                <reservoir id="res_3" regionId="reg_3" riverId="riv_5" photo="batak">
                        <name>Батак</name>
                        <depth>35</depth>
                        <damHeight>35</damHeight>
                        <length>10</length>
                        <coordinates>
                                <latitude>41.966448</latitude>
                                <longitude>24.188376</longitude>
                        </coordinates>
                        <area>22</area>
                        <water_capacity>310 000 000</water_capacity>
                </reservoir>
                <reservoir id="res_4" regionId="reg_2" riverId="riv_3" photo="ticha">
                        <name>Тича</name>
                        <depth>39.9</depth>
                        <damHeight>55.5</damHeight>
                        <length>14</length>
                        <coordinates>
                                <latitude>43.071286</latitude>
                                <longitude>26.782827</longitude>
                        </coordinates>
                        <area>18.7</area>
                        <water_capacity>311 000 000</water_capacity>
                </reservoir>
        </reservoirs>
</reservoirInfo>
